import { useEffect, useMemo, useRef, useState, type ChangeEvent, type CSSProperties } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { ArrowDownToLine, AudioLines, Check, ChevronDown, ChevronUp, FileAudio, FolderUp, Headphones, LoaderCircle, Mic, Mic2, Pause, Play, Search, Settings2, SlidersHorizontal, Sparkles, Square, Upload, X } from 'lucide-react';
import EnvironmentEmoji from '../components/EnvironmentEmoji';
import { environmentCategories, environments, getEnvironment } from '../audio/environments';
import { AudioApiError, createAmbience, createSpeech, createVoiceChange, getAudioStatus, getElevenVoices, getEnvironmentReadiness, getPreparedAmbience, getPreparedImpulse, type AudioProvenance, type ElevenVoice, type EnvironmentReadiness } from '../audio/api';
import { analyzeAudio, audioBufferToWav, createAudioPlayer, decodeAudio, measureAudio, renderMix, synthesizeAmbience, type AudioPlayer, type MixOptions } from '../audio/audio-engine';
import { deleteAudioFile, getAudioFile, saveAudioFiles } from '../audio/audio-storage';
import { readLocal, writeLocal } from '../data';
import { getStorageOwner } from '../auth/storage-owner';
import { prepareGuideUpload, GUIDE_MAX_SECONDS } from '../audio/guide-upload';
import './audio-studio.css';
import './audio-studio-upgrade.css';

type ImpulseControls={directSound:'included'|'removed';directArrivalMs:number;directWindowMs:number;predelayMode:'embedded'|'external';predelayMs:number;wet:number};
export type AudioProject = { text?:string; environment?:string; title?:string; audioFileId?:string; voiceFileId?:string; ambienceFileId?:string; guideFileId?:string;guideName?:string;impulseFileId?:string;impulseName?:string;impulseSource?:string;impulseReviewed?:boolean;impulseSettings?:ImpulseControls;ambienceName?:string;ambientProvenance?:AudioProvenance;voiceId?:string; voiceName?:string; mix?:MixOptions; audioSource?:string; ambientSource?:string; ambientReviewed?:boolean; ambientRevision?:string };
export type AudioAsset = AudioProject & { type:'audio'; title:string; subtitle:string; duration?:number; mimeType?:string };
type Props = { onNotify:(message:string)=>void; onSave:(asset:AudioAsset)=>boolean; initialProject?:AudioProject };
type Settings = { text:string;voiceId:string;mood:'natural'|'soft'|'expressive';environment:string;voiceVolume:number;ambientVolume:number;distance:number;quality:'standard'|'high'|'lossless';qualityVersion:2;ducking:boolean;spatial:boolean;capture:'clean'|'mobile';perspective:'close'|'natural'|'distant';ir:ImpulseControls };
type LocalClip = { buffer:AudioBuffer;blob:Blob;name:string;source?:'imported'|'recording'|'library';reviewed?:boolean;environment?:string };
type AmbientTrack = { buffer:AudioBuffer|null;blob:Blob|null;source:'elevenlabs'|'library'|'recording'|'uploaded'|'local'|'none';reviewed:boolean;revision?:string;name?:string;provenance?:AudioProvenance };
type Tracks = { id:string;voice:AudioBuffer;voiceBlob:Blob;ambience:AudioBuffer|null;ambienceBlob:Blob|null;environment:string;source:'elevenlabs'|'voice-changer'|'imported';text:string;voiceId?:string;voiceName:string;ambientSource:AmbientTrack['source'];ambientReviewed?:boolean;ambientRevision?:string;ambientProvenance?:AudioProvenance;ambienceName?:string;guide?:LocalClip;impulse?:LocalClip;missingAmbience?:boolean };
type Result = { buffer:AudioBuffer;blob:Blob;environment:string;text:string;voiceName:string;source:Tracks['source'];options:MixOptions;ambientSource:AmbientTrack['source'];ambientReviewed?:boolean;ambientRevision?:string;impulseSettings?:ImpulseControls;tracks?:Tracks };
type Stage = 'idle'|'voice'|'ambience'|'mix'|'restore';
const telegramVoiceId='vcYWBf5QTtDLdbfB20xT';
const defaultIR:ImpulseControls={directSound:'removed',directArrivalMs:0,directWindowMs:5,predelayMode:'embedded',predelayMs:0,wet:.18};
const defaults:Settings = {text:'',voiceId:'',mood:'natural',environment:'studio',voiceVolume:85,ambientVolume:0,distance:12,quality:'lossless',qualityVersion:2,ducking:true,spatial:true,capture:'clean',perspective:'natural',ir:defaultIR};
const clamp=(value:unknown,min:number,max:number,fallback:number)=>typeof value==='number'&&Number.isFinite(value)?Math.max(min,Math.min(max,value)):fallback;
function safeIR(value:Partial<ImpulseControls>|undefined):ImpulseControls{return {directSound:value?.directSound==='included'?'included':'removed',directArrivalMs:clamp(value?.directArrivalMs,0,500,0),directWindowMs:clamp(value?.directWindowMs,.5,30,5),predelayMode:value?.predelayMode==='external'?'external':'embedded',predelayMs:clamp(value?.predelayMs,0,200,0),wet:clamp(value?.wet,0,.65,.18)};}
function loadSettings():Settings {
  try { const saved=readLocal<Settings>('velora-audio-settings',defaults),environment=getEnvironment(saved.environment);return {...defaults,text:typeof saved.text==='string'?saved.text.slice(0,3000):'',voiceId:typeof saved.voiceId==='string'?saved.voiceId:'',mood:['natural','soft','expressive'].includes(saved.mood)?saved.mood:'natural',environment:environment.id,voiceVolume:clamp(saved.voiceVolume,0,100,85),ambientVolume:environment.sound.mode==='silent'?0:clamp(saved.ambientVolume,0,100,environment.sound.defaultVolume),distance:clamp(saved.distance,0,100,12),quality:saved.qualityVersion===2&&saved.quality==='standard'?'standard':'lossless',qualityVersion:2,ducking:saved.ducking!==false,spatial:saved.spatial!==false,capture:saved.capture==='mobile'?'mobile':'clean',perspective:['close','natural','distant'].includes(saved.perspective)?saved.perspective:'natural',ir:defaultIR}; }catch{return defaults;}
}
const mixOptions=(s:Settings):MixOptions=>({environment:s.environment,voiceVolume:s.voiceVolume,ambientVolume:s.ambientVolume,distance:s.distance,ducking:s.ducking,spatial:s.spatial,capture:s.capture,perspective:s.perspective});
const mixSignature=(options:MixOptions,ir:ImpulseControls)=>JSON.stringify({options,ir});
const formatTime=(seconds:number)=>`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
const isBrazilian=(voice:ElevenVoice)=>/brazil|brasil|pt[-_]br|brasileir/i.test(`${voice.description} ${Object.values(voice.labels).join(' ')}`);
const isPortuguese=(voice:ElevenVoice)=>isBrazilian(voice)||/portug|\bpt\b/i.test(Object.values(voice.labels).join(' '));
const directions=[{label:'Pensativo',tag:'[thoughtful]'},{label:'Sussurro',tag:'[whispering]'},{label:'Riso',tag:'[laughing]'},{label:'Suspiro',tag:'[sighs]'},{label:'Pausa curta',tag:'[short pause]'},{label:'Pausa longa',tag:'[long pause]'}];
const sourceLink=(value?:string)=>{try{const url=new URL(value||'');return ['http:','https:'].includes(url.protocol)?url.href:undefined;}catch{return undefined;}};
const errorMessage=(error:unknown)=>error instanceof Error?error.message:'Não foi possível processar o áudio.';
function checkStem(buffer:AudioBuffer,label:string) {const analysis=analyzeAudio(buffer);if(analysis.nonFiniteSamples)throw new Error(`${label} contém valores de áudio inválidos. Substitua o arquivo.`);if(analysis.silent)throw new Error(`${label} veio silencioso. Confira ou substitua o arquivo antes de aplicar.`);}
function waveformPeaks(buffer?:AudioBuffer) { if(!buffer)return Array.from({length:48},(_,i)=>10+Math.abs(Math.sin(i*1.73)*Math.cos(i*.34))*31);const data=buffer.getChannelData(0),step=Math.max(1,Math.floor(data.length/48));return Array.from({length:48},(_,i)=>{let peak=0;for(let j=i*step;j<Math.min(data.length,(i+1)*step);j+=Math.max(1,Math.floor(step/100)))peak=Math.max(peak,Math.abs(data[j]));return 5+Math.min(1,peak)*76;}); }

export default function AudioStudio({onNotify,onSave,initialProject}:Props) {
  const [settings,setSettings]=useState<Settings>(loadSettings);
  const [tab,setTab]=useState<'create'|'guide'|'import'>('create');
  const [connection,setConnection]=useState<'checking'|'connected'|'missing'|'offline'|'error'>('checking');
  const [voices,setVoices]=useState<ElevenVoice[]>([]),[nextVoicePage,setNextVoicePage]=useState<string>();
  const [losslessMaxChars,setLosslessMaxChars]=useState(1200),[losslessGuideSeconds,setLosslessGuideSeconds]=useState(80);
  const [voiceMenu,setVoiceMenu]=useState(false),[voiceQuery,setVoiceQuery]=useState(''),[loadingVoices,setLoadingVoices]=useState(false);
  const [setupOpen,setSetupOpen]=useState(false),[allEnvironments,setAllEnvironments]=useState(false),[environmentQuery,setEnvironmentQuery]=useState(''),[category,setCategory]=useState('all');
  const [advanced,setAdvanced]=useState(false),[stage,setStage]=useState<Stage>('idle'),[error,setError]=useState('');
  const [tracks,setTracks]=useState<Tracks|null>(null),[result,setResult]=useState<Result|null>(null),[importName,setImportName]=useState('');
  const [playing,setPlaying]=useState(false),[currentTime,setCurrentTime]=useState(0),[resultUrl,setResultUrl]=useState('');
  const [ambientPlaying,setAmbientPlaying]=useState(false),[ambientPreparing,setAmbientPreparing]=useState(false),[previewKind,setPreviewKind]=useState<'real'|'illustrative'|null>(null),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[mixing,setMixing]=useState(false);
  const [readiness,setReadiness]=useState<EnvironmentReadiness[]>([]),[readinessError,setReadinessError]=useState(false);
  const [voiceFilter,setVoiceFilter]=useState<'portuguese'|'all'>('portuguese'),[directionTarget,setDirectionTarget]=useState('cursor'),[directionsOpen,setDirectionsOpen]=useState(false);
  const [guide,setGuide]=useState<LocalClip|null>(null),[guideLoading,setGuideLoading]=useState(false),[recording,setRecording]=useState(false),[requestingMic,setRequestingMic]=useState(false),[recordSeconds,setRecordSeconds]=useState(0),[removeBackgroundNoise,setRemoveBackgroundNoise]=useState(false);
  const [customAmbient,setCustomAmbient]=useState<AmbientTrack|null>(null),[ambientMode,setAmbientMode]=useState<'scene'|'custom'>('scene'),[impulse,setImpulse]=useState<LocalClip|null>(null),[localLoading,setLocalLoading]=useState(false);
  const [linePreview,setLinePreview]=useState<LocalClip|null>(null),[linePreviewing,setLinePreviewing]=useState(false),[linePlaying,setLinePlaying]=useState(false),[comparison,setComparison]=useState<'mix'|'voice'|'guide'>('mix');
  const mediaRecorder=useRef<MediaRecorder|null>(null),microphone=useRef<MediaStream|null>(null),recordingTimer=useRef<number|undefined>(undefined),guideVersion=useRef(0),localVersion=useRef(0),lineVersion=useRef(0),lineRequest=useRef<AbortController|null>(null);
  const guideInput=useRef<HTMLInputElement>(null),ambientInput=useRef<HTMLInputElement>(null),impulseInput=useRef<HTMLInputElement>(null),linePlayer=useRef<HTMLAudioElement>(null),guidePlayer=useRef<HTMLAudioElement>(null);
  const resultRef=useRef(result);resultRef.current=result;
  const renderQueue=useRef(Promise.resolve());
  const settingsRef=useRef(settings);settingsRef.current=settings;
  const mounted=useRef(true),request=useRef<AbortController|null>(null),operation=useRef(0),mixVersion=useRef(0),connectionVersion=useRef(0);
  const playerRef=useRef<HTMLAudioElement>(null),previewRef=useRef<AudioPlayer|null>(null),previewRequest=useRef<AbortController|null>(null),previewVersion=useRef(0),sampleRef=useRef<HTMLAudioElement|null>(null);
  const voiceMenuRef=useRef<HTMLDivElement>(null),modalRef=useRef<HTMLDivElement>(null),importRef=useRef<HTMLInputElement>(null),scriptRef=useRef<HTMLTextAreaElement>(null);
  const lastMix=useRef(''),ambienceCache=useRef(new Map<string,AmbientTrack>()),sceneImpulseCache=useRef(new Map<string,{clip:LocalClip;controls:ImpulseControls;revision:string}>());
  const reduceMotion=useReducedMotion(),busy=stage!=='idle'||recording||requestingMic||guideLoading||localLoading||linePreviewing,finalOnly=!!result&&!tracks;
  const selectedVoice=voices.find(v=>v.id===settings.voiceId),selectedEnvironment=getEnvironment(settings.environment);
  const selectedReadiness=readiness.find(e=>e.id===settings.environment),silentEnvironment=selectedEnvironment.sound.mode==='silent'&&ambientMode!=='custom';
  const optionsSignature=mixSignature(mixOptions(settings),settings.ir);
  const playbackClip=comparison==='voice'&&result?.tracks?{blob:result.tracks.voiceBlob,buffer:result.tracks.voice}:comparison==='guide'&&result?.tracks?.guide?result.tracks.guide:result;
  const peaks=useMemo(()=>waveformPeaks(playbackClip?.buffer),[playbackClip?.buffer]);
  const metrics=useMemo(()=>result?measureAudio(result.buffer):null,[result?.buffer]);
  const filteredVoices=voices.filter(v=>(voiceFilter==='all'||isPortuguese(v))&&`${v.name} ${v.description} ${Object.values(v.labels).join(' ')}`.toLocaleLowerCase('pt-BR').includes(voiceQuery.toLocaleLowerCase('pt-BR'))).sort((a,b)=>Number(isBrazilian(b))-Number(isBrazilian(a)));
  const sentences=useMemo(()=>Array.from(settings.text.matchAll(/[^.!?\n]+(?:[.!?]+|$)/g)).filter(match=>match[0].replace(/\[[^\]]*\]/g,'').trim()).map((match,index)=>({start:match.index||0,label:`${index+1}. ${match[0].trim().slice(0,65)}`})),[settings.text]);
  const filteredEnvironments=environments.filter(e=>(allEnvironments||e.popular||e.id===settings.environment)&&(category==='all'||e.category===category)&&e.name.toLocaleLowerCase('pt-BR').includes(environmentQuery.toLocaleLowerCase('pt-BR')));
  const patch=(change:Partial<Settings>)=>setSettings(s=>({...s,...change}));
  const stopPreview=()=>{previewVersion.current++;previewRequest.current?.abort();previewRequest.current=null;previewRef.current?.stop();previewRef.current=null;setAmbientPlaying(false);setAmbientPreparing(false);setPreviewKind(null);};
  const refreshReadiness=async()=>{try{const rows=await getEnvironmentReadiness();if(mounted.current){setReadiness(rows);setReadinessError(false);}}catch{if(mounted.current)setReadinessError(true);}};
  const insertTag=(tag:string)=>{const input=scriptRef.current,chosen=directionTarget==='cursor'?undefined:sentences[Number(directionTarget)],start=chosen?.start??input?.selectionStart??settings.text.length,end=chosen?start:input?.selectionEnd??start;const insert=`${start>0&&!/\s/.test(settings.text[start-1])?' ':''}${tag} `,text=settings.text.slice(0,start)+insert+settings.text.slice(end);if(text.length>3000)return;patch({text});requestAnimationFrame(()=>{input?.focus();input?.setSelectionRange(start+insert.length,start+insert.length);});};

  const refreshConnection=async()=>{
    const version=++connectionVersion.current;setConnection('checking');
    try {const status=await getAudioStatus();if(!mounted.current||version!==connectionVersion.current)return;if(!status.configured){setConnection('missing');return;}
      if(status.speech?.losslessMaxChars)setLosslessMaxChars(status.speech.losslessMaxChars);if(status.voiceChange?.losslessMaxDurationSeconds)setLosslessGuideSeconds(status.voiceChange.losslessMaxDurationSeconds);
      const page=await getElevenVoices();if(!mounted.current||version!==connectionVersion.current)return;setVoices(page.voices);setNextVoicePage(page.nextPageToken);setConnection('connected');setError('');
      setSettings(s=>({...s,voiceId:s.voiceId||status.defaultVoiceId||page.voices.find(v=>v.id===telegramVoiceId)?.id||page.voices.find(isBrazilian)?.id||page.voices.find(isPortuguese)?.id||page.voices[0]?.id||''}));
    }catch(e){if(mounted.current&&version===connectionVersion.current){setConnection(e instanceof AudioApiError?'error':'offline');setError(errorMessage(e));}}
  };
  useEffect(()=>{mounted.current=true;void refreshConnection();void refreshReadiness();return()=>{mounted.current=false;operation.current++;mixVersion.current++;previewVersion.current++;guideVersion.current++;localVersion.current++;lineVersion.current++;request.current?.abort();previewRequest.current?.abort();lineRequest.current?.abort();previewRef.current?.stop();sampleRef.current?.pause();if(mediaRecorder.current?.state==='recording')mediaRecorder.current.stop();microphone.current?.getTracks().forEach(track=>track.stop());if(recordingTimer.current)clearInterval(recordingTimer.current);};},[]);
  useEffect(()=>{writeLocal('velora-audio-settings',settings);},[settings]);
  useEffect(()=>{if(!playbackClip){setResultUrl('');return;}const url=URL.createObjectURL(playbackClip.blob);setResultUrl(url);setPlaying(false);setCurrentTime(0);return()=>URL.revokeObjectURL(url);},[playbackClip?.blob]);
  const [guideUrl,setGuideUrl]=useState(''),[lineUrl,setLineUrl]=useState('');
  useEffect(()=>{linePlayer.current?.pause();guidePlayer.current?.pause();setLinePreview(null);setLinePlaying(false);},[settings.voiceId,settings.mood,settings.text]);
  useEffect(()=>{if(!guide){setGuideUrl('');return;}const url=URL.createObjectURL(guide.blob);setGuideUrl(url);return()=>URL.revokeObjectURL(url);},[guide?.blob]);
  useEffect(()=>{if(!linePreview){setLineUrl('');return;}const url=URL.createObjectURL(linePreview.blob);setLineUrl(url);return()=>URL.revokeObjectURL(url);},[linePreview?.blob]);
  useEffect(()=>{if(!voiceMenu)return;const listener=(e:PointerEvent)=>{if(!voiceMenuRef.current?.contains(e.target as Node))setVoiceMenu(false);};const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setVoiceMenu(false);};document.addEventListener('pointerdown',listener);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',listener);document.removeEventListener('keydown',key);};},[voiceMenu]);
  useEffect(()=>{if(!setupOpen)return;const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';modalRef.current?.querySelector<HTMLButtonElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setSetupOpen(false);if(e.key==='Tab'){const buttons=Array.from(modalRef.current?.querySelectorAll<HTMLButtonElement>('button')||[]);if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){e.preventDefault();buttons[0]?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.focus();};},[setupOpen]);

  useEffect(()=>{
    operation.current++;mixVersion.current++;guideVersion.current++;localVersion.current++;lineVersion.current++;request.current?.abort();request.current=null;lineRequest.current?.abort();stopPreview();sampleRef.current?.pause();playerRef.current?.pause();linePlayer.current?.pause();guidePlayer.current?.pause();if(mediaRecorder.current?.state==='recording')mediaRecorder.current.stop();microphone.current?.getTracks().forEach(track=>track.stop());if(recordingTimer.current)clearInterval(recordingTimer.current);setRecording(false);setRequestingMic(false);setGuideLoading(false);setLocalLoading(false);setLinePreviewing(false);setMixing(false);setStage('idle');setTracks(null);setResult(null);setGuide(null);setImpulse(null);setCustomAmbient(null);setAmbientMode('scene');setLinePreview(null);setComparison('mix');setSaved(false);setError('');lastMix.current='';
    if(!initialProject)return;const p=initialProject;
    setSettings(s=>({...s,...(p.text!==undefined?{text:p.text.slice(0,3000)}:{}),...(p.environment?{environment:getEnvironment(p.environment).id,ambientVolume:getEnvironment(p.environment).sound.defaultVolume}:{}),...(p.voiceId?{voiceId:p.voiceId}:{}),...(p.mix?{...p.mix,environment:getEnvironment(p.mix.environment).id}: {}),ir:safeIR(p.impulseSettings)}));
    if(!p.audioFileId)return;let canceled=false;setStage('restore');setError('');
    void (async()=>{try{const [finalBlob,voiceBlob,ambientBlob,guideBlob,impulseBlob]=await Promise.all([getAudioFile(p.audioFileId!),p.voiceFileId?getAudioFile(p.voiceFileId):null,p.ambienceFileId?getAudioFile(p.ambienceFileId):null,p.guideFileId?getAudioFile(p.guideFileId):null,p.impulseFileId?getAudioFile(p.impulseFileId):null]);if(!finalBlob)throw new Error('O arquivo não está mais neste navegador. O roteiro continua disponível.');
      const warnings:string[]=[];
      const optional=async(blob:Blob|null,max:number,label:string)=>{if(!blob)return null;try{return await decodeAudio(blob,max,64*1024*1024);}catch{warnings.push(`${label} não pôde ser recuperado. O arquivo final continua disponível.`);return null;}};
      const [finalBuffer,voice,ambience,guideBuffer,impulseBuffer]=await Promise.all([decodeAudio(finalBlob,305),optional(voiceBlob,300,'A voz separada'),optional(ambientBlob,181,'O ambiente'),optional(guideBlob,160,'A interpretação guia'),optional(impulseBlob,4,'A IR')]);if(canceled||!mounted.current)return;
      const restoredGuide=guideBlob&&guideBuffer?{blob:guideBlob,buffer:guideBuffer,name:p.guideName||'Interpretação guia'}:undefined,restoredImpulse:LocalClip|undefined=impulseBlob&&impulseBuffer?{blob:impulseBlob,buffer:impulseBuffer,name:p.impulseName||'IR importada',source:p.impulseSource==='library'?'library':p.impulseSource==='recording'?'recording':'imported',reviewed:p.impulseReviewed===true,...(p.impulseSource==='library'||p.impulseSource==='recording'?{environment:p.environment}: {})}:undefined;
      if(restoredGuide)setGuide(restoredGuide);if(restoredImpulse)setImpulse(restoredImpulse);
      const options=p.mix||mixOptions({...settingsRef.current,environment:getEnvironment(p.environment||'studio').id}),source:Tracks['source']=p.audioSource==='elevenlabs'?'elevenlabs':p.audioSource==='voice-changer'?'voice-changer':'imported',ambientSource:AmbientTrack['source']=['elevenlabs','library','recording','uploaded','local'].includes(p.ambientSource||'')?p.ambientSource as AmbientTrack['source']:'none';
      const missingAmbience=!!p.ambienceFileId&&!ambience;
      const restored:Tracks|undefined=voice&&voiceBlob?{id:crypto.randomUUID(),voice,voiceBlob,ambience,ambienceBlob:ambientBlob,environment:options.environment,source,text:p.text||'',voiceId:p.voiceId,voiceName:p.voiceName||'Áudio salvo',ambientSource,ambientReviewed:p.ambientReviewed,ambientRevision:p.ambientRevision,ambientProvenance:p.ambientProvenance,ambienceName:p.ambienceName,guide:restoredGuide,impulse:restoredImpulse,missingAmbience}:undefined;
      if(ambientSource==='uploaded'&&ambience&&ambientBlob){setCustomAmbient({buffer:ambience,blob:ambientBlob,source:'uploaded',reviewed:false,name:p.ambienceName||'Ambiente próprio'});setAmbientMode('custom');}
      setResult({buffer:finalBuffer,blob:finalBlob,environment:options.environment,text:p.text||'',voiceName:p.voiceName||'Áudio salvo',source,options,ambientSource,ambientReviewed:p.ambientReviewed,ambientRevision:p.ambientRevision,impulseSettings:safeIR(p.impulseSettings),tracks:restored});setSaved(true);
      if(restored){lastMix.current=restored.id+mixSignature(options,safeIR(p.impulseSettings));setTracks(restored);}
      else setError('Este projeto contém somente o arquivo final. Você pode ouvir e baixar; importe a voz separada para criar um novo mix.');
      if(missingAmbience)setError('A faixa de fundo salva não está mais neste navegador. O WAV final foi preservado. Atualize o ambiente para recuperar o fundo, ou deixe o volume dele em zero para refazer só a voz.');
      if(warnings.length)setError(warnings.join(' '));
      if(source==='imported')setTab('import');else if(source==='voice-changer')setTab('guide');else setTab('create');
    }catch(e){if(!canceled&&mounted.current)setError(errorMessage(e));}finally{if(!canceled&&mounted.current)setStage('idle');}})();return()=>{canceled=true;};
  },[initialProject]);

  const mixTracks=async(t:Tracks,options:MixOptions,irOverride?:ImpulseControls)=>{
    const version=++mixVersion.current,impulseSettings={...(irOverride||settingsRef.current.ir)};setMixing(true);playerRef.current?.pause();setPlaying(false);
    const previous=renderQueue.current;let release!:()=>void;renderQueue.current=new Promise<void>(resolve=>{release=resolve;});
    try{await previous;if(!mounted.current||version!==mixVersion.current)return;const buffer=await renderMix(t.voice,t.ambience,options,{ambienceSource:t.ambientSource==='uploaded'?'custom':'scene',...(t.impulse?{impulseResponse:{...impulseSettings,buffer:t.impulse.buffer,label:t.impulse.name,source:t.impulse.source==='recording'||t.impulse.source==='library'?'recorded':'imported'}}:{})});if(!mounted.current||version!==mixVersion.current)return;
      const blob=audioBufferToWav(buffer);setResult({buffer,blob,environment:options.environment,text:t.text,voiceName:t.voiceName,source:t.source,options,ambientSource:t.ambientSource,ambientReviewed:t.ambientReviewed,ambientRevision:t.ambientRevision,impulseSettings,tracks:t});setSaved(false);lastMix.current=t.id+mixSignature(options,impulseSettings);
    }finally{release();if(mounted.current&&version===mixVersion.current)setMixing(false);}
  };
  useEffect(()=>{
    if(!tracks||busy||saving||tracks.environment!==settings.environment||(ambientMode==='custom')!==(tracks.ambientSource==='uploaded')||(tracks.missingAmbience&&!silentEnvironment&&settings.ambientVolume>0))return;const signature=tracks.id+optionsSignature;if(signature===lastMix.current)return;
    const timer=setTimeout(()=>void mixTracks(tracks,mixOptions(settingsRef.current)).catch(e=>{if(mounted.current)setError(errorMessage(e));}),350);return()=>clearTimeout(timer);
  },[tracks,optionsSignature,busy,saving,settings.environment,ambientMode]);

  const getAmbience=async(environment:string,signal:AbortSignal,allowGenerate=true):Promise<AmbientTrack>=>{
    if(ambientMode==='custom'){if(customAmbient)return customAmbient;throw new Error('Importe um som de fundo próprio antes de aplicar.');}
    if(getEnvironment(environment).sound.mode==='silent')return {buffer:null,blob:null,source:'none',reviewed:true};
    // Always consult the server first: an approved recording can replace an AI candidate.
    let asset;
    try{asset=await getPreparedAmbience(environment,signal);}catch(e){
      if(!(e instanceof AudioApiError&&e.code==='AMBIENCE_NOT_READY'))throw e;
      if(!allowGenerate){void refreshReadiness();throw new Error('Este som preparado não está mais disponível. Atualize a biblioteca ou use “Gerar som do ambiente” para preparar outro.');}
      if(connection!=='connected')throw new Error('Este ambiente ainda não tem um som preparado. Conecte ElevenLabs para gerar ou adicione uma gravação à biblioteca. Sua voz continua disponível.');
      asset=await createAmbience(environment,signal);void refreshReadiness();
    }
    if(signal.aborted)throw new DOMException('Cancelado','AbortError');
    const origin:AmbientTrack['source']=asset.source==='library'?'library':asset.source==='recording'?'recording':'elevenlabs';
    const key=`${environment}:${origin}:${asset.revision}:${asset.reviewed}`,cached=ambienceCache.current.get(key);if(cached)return cached;
    const buffer=await decodeAudio(asset.blob,181,64*1024*1024);checkStem(buffer,'O som deste ambiente');
    const value:AmbientTrack={buffer,blob:asset.blob,source:origin,reviewed:asset.reviewed,revision:asset.revision,name:asset.provenance?.label,provenance:asset.provenance};
    ambienceCache.current.set(key,value);if(ambienceCache.current.size>8)ambienceCache.current.delete(ambienceCache.current.keys().next().value!);return value;
  };
  const acceptGuide=async(blob:Blob,name:string,version=++guideVersion.current)=>{
    setGuideLoading(true);setError('');
    try{const buffer=await decodeAudio(blob,GUIDE_MAX_SECONDS,30*1024*1024);checkStem(buffer,'A interpretação guia');const wav=await prepareGuideUpload(buffer);if(!mounted.current||version!==guideVersion.current)return;setGuide({buffer,blob:wav,name});setRemoveBackgroundNoise(false);}
    catch(e){if(mounted.current&&version===guideVersion.current)setError(errorMessage(e));}finally{if(mounted.current&&version===guideVersion.current)setGuideLoading(false);}
  };
  const uploadGuide=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(file&&!busy&&!saving)void acceptGuide(file,file.name);};
  const stopRecording=()=>{if(recordingTimer.current)clearInterval(recordingTimer.current);recordingTimer.current=undefined;if(mediaRecorder.current?.state==='recording')mediaRecorder.current.stop();microphone.current?.getTracks().forEach(track=>track.stop());microphone.current=null;setRecording(false);};
  const startRecording=async()=>{
    if(busy||saving)return;if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setError('Este navegador não oferece gravação. Use um arquivo de áudio ou abra o site em localhost/HTTPS.');return;}
    stopPreview();sampleRef.current?.pause();playerRef.current?.pause();linePlayer.current?.pause();guidePlayer.current?.pause();setRequestingMic(true);setError('');const version=++guideVersion.current;
    try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});if(!mounted.current||version!==guideVersion.current){stream.getTracks().forEach(track=>track.stop());return;}
      microphone.current=stream;const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(value=>MediaRecorder.isTypeSupported(value));const recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined),chunks:BlobPart[]=[];mediaRecorder.current=recorder;
      recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recorder.onerror=()=>{stopRecording();if(mounted.current)setError('A gravação foi interrompida pelo navegador. Tente novamente ou importe um arquivo.');};
      recorder.onstop=()=>{stream.getTracks().forEach(track=>track.stop());if(mounted.current&&version===guideVersion.current)void acceptGuide(new Blob(chunks,{type:recorder.mimeType||'audio/webm'}),'Minha interpretação gravada',version);};
      recorder.start(500);setRecordSeconds(0);setRecording(true);const started=performance.now();recordingTimer.current=window.setInterval(()=>{const seconds=Math.floor((performance.now()-started)/1000);setRecordSeconds(seconds);if(seconds>=GUIDE_MAX_SECONDS)stopRecording();},250);
    }catch(e){microphone.current?.getTracks().forEach(track=>track.stop());microphone.current=null;if(mounted.current&&version===guideVersion.current)setError(e instanceof DOMException&&e.name==='NotAllowedError'?'O microfone não foi autorizado. Permita o acesso no navegador ou importe um arquivo.':'Não foi possível acessar o microfone. Confira se outro aplicativo está usando o dispositivo.');}
    finally{if(mounted.current&&version===guideVersion.current)setRequestingMic(false);}
  };
  const importLocalResource=async(event:ChangeEvent<HTMLInputElement>,kind:'ambience'|'impulse')=>{
    const file=event.target.files?.[0];event.target.value='';if(!file||busy||saving)return;const version=++localVersion.current;stopPreview();setLocalLoading(true);setError('');
    try{const buffer=await decodeAudio(file,kind==='impulse'?4:180,kind==='impulse'?8*1024*1024:64*1024*1024);checkStem(buffer,kind==='impulse'?'A resposta de impulso':'O ambiente próprio');if(kind==='impulse'&&buffer.numberOfChannels>2)throw new Error('Escolha uma IR mono ou estéreo, com até 4 segundos.');if(!mounted.current||version!==localVersion.current)return;
      if(kind==='ambience'){const ambient:AmbientTrack={buffer,blob:file,source:'uploaded',reviewed:false,name:file.name};setCustomAmbient(ambient);setAmbientMode('custom');patch({ambientVolume:settings.ambientVolume||30});if(tracks){const next={...tracks,id:crypto.randomUUID(),ambience:buffer,ambienceBlob:file,environment:settings.environment,ambientSource:'uploaded' as const,ambientReviewed:false,ambienceName:file.name,missingAmbience:false};setTracks(next);}}
      else{const clip:LocalClip={buffer,blob:file,name:file.name,source:'imported',reviewed:false};setImpulse(clip);patch({spatial:true,ir:defaultIR});if(tracks)setTracks({...tracks,id:crypto.randomUUID(),impulse:clip});}
      onNotify(kind==='impulse'?'IR carregada. Confira os metadados antes de usar.':'Ambiente importado. Ajuste o fundo sem gerar outra voz.');
    }catch(e){if(mounted.current&&version===localVersion.current)setError(errorMessage(e));}finally{if(mounted.current&&version===localVersion.current)setLocalLoading(false);}
  };
  const loadSceneImpulse=async()=>{
    if(busy||saving)return;const version=++localVersion.current;setLocalLoading(true);setError('');const environment=settings.environment;
    try{const asset=await getPreparedImpulse(environment),buffer=await decodeAudio(asset.blob,4,8*1024*1024);checkStem(buffer,'A resposta de sala');if(buffer.numberOfChannels>2)throw new Error('A resposta de sala deve ser mono ou estéreo.');if(!mounted.current||version!==localVersion.current)return;const clip:LocalClip={blob:asset.blob,buffer,name:`Resposta de sala · ${getEnvironment(environment).name}`,source:asset.metadata.source,reviewed:asset.metadata.reviewed,environment};setImpulse(clip);patch({spatial:true,ir:safeIR(asset.metadata.acoustic)});if(tracks)setTracks({...tracks,id:crypto.randomUUID(),impulse:clip});}
    catch(e){if(mounted.current&&version===localVersion.current)setError(errorMessage(e));}finally{if(mounted.current&&version===localVersion.current)setLocalLoading(false);}
  };
  // A scene IR belongs to its location. Imported IRs remain an explicit user choice.
  const resolveSceneImpulse=async(snapshot:Settings,signal:AbortSignal):Promise<{clip?:LocalClip;controls:ImpulseControls}>=>{
    const empty={clip:undefined,controls:defaultIR};
    if(!snapshot.spatial)return empty;
    if(impulse?.source==='imported')return {clip:impulse,controls:snapshot.ir};
    if(impulse?.environment===snapshot.environment)return {clip:impulse,controls:snapshot.ir};
    const known=readiness.find(row=>row.id===snapshot.environment)?.resources?.ir;
    let prepared=sceneImpulseCache.current.get(snapshot.environment);
    if(!prepared||(known&&prepared.revision!==known.revision)){
      try{
        const asset=await getPreparedImpulse(snapshot.environment,signal),buffer=await decodeAudio(asset.blob,4,8*1024*1024);
        checkStem(buffer,'A resposta de sala');if(buffer.numberOfChannels>2)throw new Error('A resposta de sala deve ser mono ou estéreo.');
        prepared={clip:{blob:asset.blob,buffer,name:'Resposta de sala · '+getEnvironment(snapshot.environment).name,source:asset.metadata.source,reviewed:asset.metadata.reviewed,environment:snapshot.environment},controls:safeIR(asset.metadata.acoustic),revision:asset.metadata.revision};
        sceneImpulseCache.current.set(snapshot.environment,prepared);
      }catch(e){
        if(!(e instanceof AudioApiError&&e.code==='AUDIO_RESOURCE_NOT_READY'))throw e;
        prepared=undefined;
      }
    }
    if(signal.aborted||!mounted.current)throw new DOMException('Cancelado','AbortError');
    if(settingsRef.current.environment===snapshot.environment){setImpulse(prepared?.clip||null);setSettings(current=>current.environment===snapshot.environment?{...current,ir:prepared?.controls||defaultIR}:current);}
    return prepared||empty;
  };
  const toggleSpatial=async()=>{
    if(busy||saving||finalOnly)return;
    if(settings.spatial||!tracks){patch({spatial:!settings.spatial});return;}
    const id=++operation.current,controller=new AbortController(),base=tracks,snapshot={...settingsRef.current,environment:tracks.environment,spatial:true};
    request.current=controller;setStage('mix');setError('');
    try{const acoustics=await resolveSceneImpulse(snapshot,controller.signal);if(!mounted.current||controller.signal.aborted||id!==operation.current)return;const next={...base,id:crypto.randomUUID(),impulse:acoustics.clip};patch({spatial:true,ir:acoustics.controls});setTracks(next);await mixTracks(next,mixOptions(snapshot),acoustics.controls);}
    catch(e){if(mounted.current&&!controller.signal.aborted&&id===operation.current)setError(errorMessage(e));}
    finally{if(mounted.current&&id===operation.current)setStage('idle');if(request.current===controller)request.current=null;}
  };
  const selectEnvironment=(environment:string)=>{
    stopPreview();if(impulse?.source!=='imported'&&impulse?.environment!==environment)setImpulse(null);
    patch({environment,ambientVolume:ambientMode==='custom'?settings.ambientVolume:getEnvironment(environment).sound.defaultVolume});
  };
  const previewActualLine=async()=>{
    if(busy||saving||connection!=='connected'||!settings.voiceId||!settings.text.trim())return;stopPreview();sampleRef.current?.pause();playerRef.current?.pause();linePlayer.current?.pause();guidePlayer.current?.pause();setLinePlaying(false);setError('');setLinePreviewing(true);const version=++lineVersion.current,controller=new AbortController();lineRequest.current=controller;
    const selected=directionTarget==='cursor'?undefined:sentences[Number(directionTarget)],excerpt=selected?settings.text.slice(selected.start,sentences[Number(directionTarget)+1]?.start).trim():settings.text.trim(),text=excerpt.length>240?excerpt.slice(0,240).replace(/\s+\S*$/,''):excerpt;
    try{const blob=await createSpeech({text:text||settings.text.trim().slice(0,240),voiceId:settings.voiceId,mood:settings.mood,quality:settings.quality},controller.signal),buffer=await decodeAudio(blob,60);checkStem(buffer,'A prévia da voz');if(!mounted.current||controller.signal.aborted||version!==lineVersion.current)return;setLinePreview({blob,buffer,name:selectedVoice?.name||'Voz selecionada'});onNotify('Prévia gerada com seu roteiro. Ouça antes de criar o áudio completo.');}
    catch(e){if(mounted.current&&version===lineVersion.current&&!(e instanceof DOMException&&e.name==='AbortError'))setError(errorMessage(e));}finally{if(mounted.current&&version===lineVersion.current){setLinePreviewing(false);lineRequest.current=null;}}
  };
  const generate=async()=>{
    if(busy||saving||connection!=='connected'||(tab==='guide'?!guide:!settings.text.trim())||!settings.voiceId)return;
    if(settings.quality==='lossless'&&(tab==='guide'?(guide?.buffer.duration||0)>losslessGuideSeconds:settings.text.length>losslessMaxChars)){setError(tab==='guide'?'Use uma interpretação de até '+losslessGuideSeconds+' segundos ou selecione Arquivo compacto.':'Para voz sem compressão, use até '+losslessMaxChars+' caracteres por áudio ou selecione Arquivo compacto.');return;}
    stopPreview();sampleRef.current?.pause();guidePlayer.current?.pause();linePlayer.current?.pause();playerRef.current?.pause();setError('');const snapshot={...settings},controller=new AbortController();request.current=controller;const id=++operation.current;setStage('voice');
    try{const blob=tab==='guide'&&guide?(await createVoiceChange({audio:guide.blob,voiceId:snapshot.voiceId,quality:snapshot.quality,removeBackgroundNoise},controller.signal)).blob:await createSpeech({text:snapshot.text,voiceId:snapshot.voiceId,mood:snapshot.mood,quality:snapshot.quality},controller.signal);const voice=await decodeAudio(blob,300);checkStem(voice,'A voz gerada');if(controller.signal.aborted||!mounted.current||id!==operation.current)return;
      const base:Tracks={id:crypto.randomUUID(),voice,voiceBlob:blob,ambience:null,ambienceBlob:null,environment:'studio',source:tab==='guide'?'voice-changer':'elevenlabs',text:tab==='guide'?'':snapshot.text,voiceId:snapshot.voiceId,voiceName:selectedVoice?.name||'ElevenLabs',ambientSource:'none',guide:tab==='guide'&&guide?guide:undefined};setComparison('mix');
      setTracks(base);setStage('mix');await mixTracks(base,{...mixOptions(snapshot),environment:'studio'});
      setStage('ambience');
      const [ambient,acoustics]=await Promise.all([
        (getEnvironment(snapshot.environment).sound.mode==='bed'||ambientMode==='custom')&&snapshot.ambientVolume>0?getAmbience(snapshot.environment,controller.signal):Promise.resolve<AmbientTrack>({buffer:null,blob:null,source:'none',reviewed:true}),
        resolveSceneImpulse(snapshot,controller.signal),
      ]);
      if(controller.signal.aborted||!mounted.current||id!==operation.current)return;
      const complete:Tracks={...base,id:crypto.randomUUID(),ambience:ambient.buffer,ambienceBlob:ambient.blob,environment:snapshot.environment,ambientSource:ambient.source,ambientReviewed:ambient.reviewed,ambientRevision:ambient.revision,ambientProvenance:ambient.provenance,ambienceName:ambient.name,impulse:acoustics.clip};
      setTracks(complete);setStage('mix');await mixTracks(complete,mixOptions(snapshot),acoustics.controls);
      if(mounted.current)onNotify('Seu áudio está pronto. Ouça, ajuste o mix e baixe.');
    }catch(e){if(mounted.current&&!(e instanceof DOMException&&e.name==='AbortError'))setError(errorMessage(e));}finally{if(mounted.current&&id===operation.current){request.current=null;setStage('idle');}}
  };
  const applyEnvironment=async()=>{
    if(!tracks||busy||saving)return;stopPreview();setError('');const snapshot={...settings},base=tracks,controller=new AbortController();request.current=controller;const id=++operation.current;setStage('ambience');
    try{const [ambient,acoustics]=await Promise.all([snapshot.ambientVolume>0?getAmbience(snapshot.environment,controller.signal):Promise.resolve<AmbientTrack>({buffer:null,blob:null,source:'none',reviewed:true}),resolveSceneImpulse(snapshot,controller.signal)]);if(!mounted.current||controller.signal.aborted||id!==operation.current)return;
      const next:Tracks={...base,id:crypto.randomUUID(),ambience:ambient.buffer,ambienceBlob:ambient.blob,environment:snapshot.environment,ambientSource:ambient.source,ambientReviewed:ambient.reviewed,ambientRevision:ambient.revision,ambientProvenance:ambient.provenance,ambienceName:ambient.name,impulse:acoustics.clip,missingAmbience:false};setTracks(next);setStage('mix');await mixTracks(next,mixOptions(snapshot),acoustics.controls);
    }catch(e){if(mounted.current&&!(e instanceof DOMException&&e.name==='AbortError'))setError(errorMessage(e));}finally{if(mounted.current&&id===operation.current){request.current=null;setStage('idle');}}
  };
  const importAudio=async(event:ChangeEvent<HTMLInputElement>)=>{
    const file=event.target.files?.[0];event.target.value='';if(!file||busy||saving)return;if(file.size>30*1024*1024){setError('Escolha um áudio de até 30 MB e 3 minutos.');return;}
    stopPreview();setError('');setStage('mix');const id=++operation.current;
    try{const voice=await decodeAudio(file,180);checkStem(voice,'O áudio importado');if(!mounted.current||id!==operation.current)return;const next:Tracks={id:crypto.randomUUID(),voice,voiceBlob:file,ambience:null,ambienceBlob:null,environment:'studio',source:'imported',text:'',voiceName:file.name.replace(/\.[^.]+$/,''),ambientSource:'none',impulse:impulse?.source==='imported'?impulse:undefined};setTracks(next);setImportName(file.name);setComparison('mix');await mixTracks(next,{...mixOptions(settingsRef.current),environment:'studio'});}
    catch(e){if(mounted.current)setError(errorMessage(e));}finally{if(mounted.current&&id===operation.current)setStage('idle');}
  };
  const toggleAmbient=async(illustrative=false,allowGenerate=false)=>{
    if(ambientPlaying){stopPreview();return;}sampleRef.current?.pause();playerRef.current?.pause();setPlaying(false);setError('');const id=++previewVersion.current,environment=settings.environment;setAmbientPlaying(true);setAmbientPreparing(true);setPreviewKind(illustrative?'illustrative':'real');
    const controller=new AbortController();previewRequest.current=controller;
    try{const buffer=illustrative?await synthesizeAmbience(environment,10):(await getAmbience(environment,controller.signal,allowGenerate)).buffer;if(!mounted.current||id!==previewVersion.current)return;if(!buffer){stopPreview();return;}const previewPlayer=await createAudioPlayer(buffer,undefined,()=>{if(mounted.current&&id===previewVersion.current){previewRef.current=null;setAmbientPlaying(false);setPreviewKind(null);}});if(!mounted.current||id!==previewVersion.current){previewPlayer.stop();return;}previewRef.current=previewPlayer;setAmbientPreparing(false);previewRequest.current=null;}
    catch(e){if(mounted.current&&id===previewVersion.current){setAmbientPlaying(false);setAmbientPreparing(false);setPreviewKind(null);previewRequest.current=null;if(!(e instanceof DOMException&&e.name==='AbortError'))setError(errorMessage(e));}}
  };
  const previewVoice=(voice:ElevenVoice)=>{if(!voice.previewUrl)return;stopPreview();playerRef.current?.pause();setPlaying(false);sampleRef.current?.pause();const audio=new Audio(voice.previewUrl);sampleRef.current=audio;void audio.play().catch(()=>onNotify('Não foi possível tocar essa amostra de voz.'));};
  const loadMoreVoices=async()=>{if(!nextVoicePage||loadingVoices)return;setLoadingVoices(true);try{const page=await getElevenVoices(nextVoicePage);if(mounted.current){setVoices(existing=>[...existing,...page.voices.filter(v=>!existing.some(e=>e.id===v.id))]);setNextVoicePage(page.nextPageToken);}}catch(e){if(mounted.current)setError(errorMessage(e));}finally{if(mounted.current)setLoadingVoices(false);}};
  const togglePlay=async()=>{const player=playerRef.current;if(!player||!result||!playbackClip)return;stopPreview();sampleRef.current?.pause();linePlayer.current?.pause();guidePlayer.current?.pause();if(!player.paused){player.pause();setPlaying(false);return;}const levels=[result.buffer,result.tracks?.voice,result.tracks?.guide?.buffer].filter((buffer):buffer is AudioBuffer=>!!buffer).map(buffer=>analyzeAudio(buffer).activeRms).filter(level=>level>.00001),level=analyzeAudio(playbackClip.buffer).activeRms;player.volume=level>.00001?Math.min(1,Math.min(.12,...levels)/level):1;if(player.ended)player.currentTime=0;try{await player.play();setPlaying(true);}catch{onNotify('Não foi possível reproduzir. Baixe o WAV para ouvir.');}};
  const download=()=>{if(!result||mixing||busy)return;const link=document.createElement('a'),url=URL.createObjectURL(result.blob);link.href=url;link.download=`velora-${getEnvironment(result.environment).name.toLocaleLowerCase('pt-BR')}-${Date.now()}.wav`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const downloadStem=(blob:Blob,label:string)=>{const extension=blob.type.includes('mpeg')?'mp3':blob.type.includes('mp4')?'m4a':blob.type.includes('ogg')?'ogg':blob.type.includes('flac')?'flac':blob.type.includes('webm')?'webm':'wav',url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`velora-${label}.${extension}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const toggleLine=async()=>{const player=linePlayer.current;if(!player)return;if(!player.paused){player.pause();return;}stopPreview();sampleRef.current?.pause();playerRef.current?.pause();guidePlayer.current?.pause();try{await player.play();}catch{onNotify('Não foi possível reproduzir a prévia.');}};
  const save=async()=>{
    if(!result||busy||mixing||saving||saved)return;setSaving(true);const ids:string[]=[],id=`audio-${crypto.randomUUID()}`,snapshot=result,stems=result.tracks,owner=getStorageOwner();
    try{let voiceFileId:string|undefined,ambienceFileId:string|undefined,guideFileId:string|undefined,impulseFileId:string|undefined;const files=[{id,blob:snapshot.blob}];
      if(stems){voiceFileId=`${id}-voice`;files.push({id:voiceFileId,blob:stems.voiceBlob});if(stems.ambienceBlob){ambienceFileId=`${id}-ambient`;files.push({id:ambienceFileId,blob:stems.ambienceBlob});}if(stems.guide){guideFileId=`${id}-guide`;files.push({id:guideFileId,blob:stems.guide.blob});}if(stems.impulse){impulseFileId=`${id}-ir`;files.push({id:impulseFileId,blob:stems.impulse.blob});}}
      await saveAudioFiles(files);ids.push(...files.map(file=>file.id));if(!mounted.current||!owner||getStorageOwner()!==owner)throw new Error('A sessão mudou antes de salvar o projeto.');
      const accepted=onSave({type:'audio',title:snapshot.source==='imported'?snapshot.voiceName:snapshot.source==='voice-changer'?`Interpretação · ${snapshot.voiceName}`:snapshot.text.trim().slice(0,42)||'Meu áudio',subtitle:`${snapshot.voiceName} · ${getEnvironment(snapshot.environment).name}`,text:snapshot.text,environment:snapshot.environment,audioFileId:id,voiceFileId,ambienceFileId,guideFileId,guideName:stems?.guide?.name,impulseFileId,impulseName:stems?.impulse?.name,impulseSource:stems?.impulse?.source,impulseReviewed:stems?.impulse?.reviewed,impulseSettings:snapshot.impulseSettings,ambienceName:stems?.ambienceName,voiceId:stems?.voiceId,voiceName:snapshot.voiceName,mix:snapshot.options,audioSource:snapshot.source,ambientSource:snapshot.ambientSource,ambientReviewed:snapshot.ambientReviewed,ambientRevision:snapshot.ambientRevision,ambientProvenance:stems?.ambientProvenance,duration:snapshot.buffer.duration,mimeType:'audio/wav'});
      if(!accepted)throw new Error('Não foi possível salvar o projeto. Baixe o WAV para guardar o áudio.');if(mounted.current&&resultRef.current===snapshot)setSaved(true);
    }catch(e){await Promise.all(ids.map(fileId=>deleteAudioFile(fileId,owner||undefined).catch(()=>{})));if(mounted.current)setError(errorMessage(e));}finally{if(mounted.current)setSaving(false);}
  };
  const cancel=()=>{request.current?.abort();lineRequest.current?.abort();lineVersion.current++;setLinePreviewing(false);operation.current++;request.current=null;setStage('idle');};
  const pendingEnvironment=!!tracks&&(tracks.environment!==settings.environment||(ambientMode==='custom')!==(tracks.ambientSource==='uploaded'));
  const needsAmbience=!!tracks&&!silentEnvironment&&settings.ambientVolume>0&&!tracks.ambience;
  const pending=pendingEnvironment||needsAmbience;
  const losslessOverLimit=settings.quality==='lossless'&&(tab==='guide'?(guide?.buffer.duration||0)>losslessGuideSeconds:tab==='create'&&settings.text.length>losslessMaxChars);
  const stageText=requestingMic?'Aguardando microfone…':recording?`Gravando · ${formatTime(recordSeconds)}`:guideLoading?'Preparando sua guia…':localLoading?'Lendo o arquivo local…':linePreviewing?'Gerando a prévia da frase…':stage==='voice'?(tab==='guide'?'Convertendo sua interpretação…':'Criando a voz com Eleven v3…'):stage==='ambience'?'Preparando o som ambiente…':stage==='restore'?'Abrindo seu áudio…':'Finalizando o mix…';
  const hasPreparedSound=ambientMode==='custom'?!!customAmbient:selectedReadiness?.status==='approved'||selectedReadiness?.status==='recorded'||selectedReadiness?.status==='generated';
  const soundStatus=ambientMode==='custom'?'Seu arquivo de ambiente':silentEnvironment?'Somente acústica':selectedReadiness?.status==='approved'?'Som revisado':selectedReadiness?.status==='recorded'?'Gravação de ambiente · ainda não revisada':selectedReadiness?.status==='generated'?'Som gerado por IA · ainda não revisado':readinessError?'Biblioteca indisponível':'Som ainda não preparado';

  return <motion.div className={'audio-studio as-clean '+(reduceMotion?'as-reduced-motion':'')} initial={{opacity:0,y:reduceMotion?0:8}} animate={{opacity:1,y:0}} transition={{duration:.3}}>
    <header className="as-page-header"><div><h1>Uma voz. <span>Todo um lugar.</span></h1><p>Escreva ou interprete. Depois, encontre a atmosfera certa.</p></div><button className={'as-connection '+connection} onClick={()=>setSetupOpen(true)}><span/>{connection==='connected'?'ElevenLabs conectado':connection==='checking'?'Verificando conexão…':'Configurar ElevenLabs'}<Settings2 size={14}/></button></header>
    <div className="as-workspace"><section className="as-composer" aria-label="Preparar voz e ambiente">
      <div className="as-tabs" role="group" aria-label="Como começar">{[{id:'create',name:'Texto',icon:Mic2},{id:'guide',name:'Interpretação',icon:Mic},{id:'import',name:'Meu áudio',icon:FolderUp}].map(mode=><button key={mode.id} className={tab===mode.id?'active':''} aria-pressed={tab===mode.id} disabled={busy||saving} onClick={()=>setTab(mode.id as typeof tab)}><mode.icon size={15}/>{mode.name}</button>)}</div>
      {tab==='create'?<>
        <div className="as-section-heading"><label htmlFor="voice-script">O que você quer dizer?</label><button className="as-text-action" disabled={busy||saving} onClick={()=>patch({text:'Oi, tô saindo agora. Pera… deixa eu pegar minha chave. A chuva apertou aqui, então acho que vou demorar só mais um pouquinho, tá?'})}>Usar um exemplo</button></div>
        <div className="as-script-field"><textarea ref={scriptRef} id="voice-script" maxLength={3000} value={settings.text} onChange={event=>patch({text:event.target.value})} placeholder="Escreva como você fala. Frases curtas, pausas naturais e uma intenção clara." disabled={busy||saving}/><div className="as-script-footer"><span>Eleven v3 · português</span><span>{settings.text.length.toLocaleString('pt-BR')} / {settings.quality==='lossless'?losslessMaxChars.toLocaleString('pt-BR'):'3.000'}</span></div></div>
        {losslessOverLimit&&<p className="as-limit-help" role="status">Sem compressão aceita até {losslessMaxChars.toLocaleString('pt-BR')} caracteres. Divida o roteiro ou escolha Arquivo compacto em Qualidade e acústica.</p>}
        <button className="as-directions-toggle" aria-expanded={directionsOpen} aria-controls="as-direction-editor" onClick={()=>setDirectionsOpen(value=>!value)}><SlidersHorizontal size={14}/>Dirigir uma frase{directionsOpen?<ChevronUp size={13}/>:<ChevronDown size={13}/>}</button>
        {directionsOpen&&<div className="as-direction-editor" id="as-direction-editor"><label htmlFor="as-direction-target">Aplicar a direção em</label><select id="as-direction-target" value={directionTarget} disabled={busy||saving} onChange={event=>setDirectionTarget(event.target.value)}><option value="cursor">Posição do cursor</option>{sentences.map((sentence,index)=><option key={index} value={index}>{sentence.label}</option>)}</select><div className="as-delivery-tags" role="group" aria-label="Direções disponíveis">{directions.map(direction=><button key={direction.tag} disabled={busy||saving} title={'Inserir '+direction.tag+' no roteiro'} onClick={()=>insertTag(direction.tag)}>{direction.label}</button>)}</div><p>As direções ficam visíveis no roteiro. A resposta varia conforme a voz; use poucas e ouça o resultado.</p></div>}
      </>:tab==='guide'?<>
        <div className="as-section-heading"><span className="as-title">Sua interpretação, outra voz.</span><span className="as-small-badge">Voice Changer v2</span></div>
        <p className="as-intro-note">Grave o ritmo e a intenção que você quer ouvir. A conversão usa Multilingual v2; o modo texto usa Eleven v3.</p>
        <div className={'as-guide-zone '+(recording?'is-recording':'')}><div className="as-guide-symbol">{recording?<span/>:<Mic size={24}/>}</div><strong>{recording?'Gravando sua interpretação':guide?guide.name:'Comece com a sua própria voz'}</strong><span>{recording?formatTime(recordSeconds)+' / 2:00':guide?formatTime(guide.buffer.duration)+' · guia pronta':'Um lugar silencioso ajuda a preservar a interpretação.'}</span><div className="as-guide-actions"><button className="as-secondary-button" disabled={(!recording&&busy)||saving} onClick={recording?stopRecording:startRecording}>{recording?<Square size={13}/>:<Mic size={14}/>} {recording?'Parar gravação':requestingMic?'Aguardando permissão…':'Gravar agora'}</button><button className="as-secondary-button" disabled={busy||saving} onClick={()=>guideInput.current?.click()}><Upload size={14}/>Importar guia</button></div><small>Até 120 segundos · importação de até 30 MB. A guia é otimizada antes do envio e só sai do dispositivo quando você pede a conversão.</small></div>
        <input ref={guideInput} type="file" hidden accept="audio/*,.wav,.mp3,.m4a,.ogg,.flac,.webm" onChange={uploadGuide}/>
        {guide&&<div className="as-guide-loaded"><audio ref={guidePlayer} controls src={guideUrl||undefined} preload="metadata" aria-label="Ouvir interpretação original" onPlay={()=>{if(recording||requestingMic){guidePlayer.current?.pause();return;}stopPreview();sampleRef.current?.pause();playerRef.current?.pause();linePlayer.current?.pause();}}/><button className="as-text-action" disabled={busy||saving} onClick={()=>{guideVersion.current++;setGuide(null);}}>Remover guia<X size={12}/></button><label className="as-checkbox"><input type="checkbox" checked={removeBackgroundNoise} disabled={busy||saving} onChange={event=>setRemoveBackgroundNoise(event.target.checked)}/><span>Remover ruído da guia na conversão<small>Use apenas se houver ruído. A limpeza pode alterar detalhes da voz.</small></span></label></div>}
      </>:<>
        <div className="as-section-heading"><span className="as-title">Sua voz já está pronta?</span></div><p className="as-intro-note">Importe a fala e faça o mix aqui, sem gerar outra voz.</p><button className="as-import-zone" onClick={()=>importRef.current?.click()} disabled={busy||saving}><FileAudio size={25}/><strong>{importName||'Escolher arquivo de voz'}</strong><span>MP3, WAV, M4A, OGG ou FLAC</span><small>Até 3 minutos · 30 MB</small></button><input ref={importRef} type="file" accept="audio/*,.mp3,.wav,.m4a,.ogg,.flac" hidden onChange={importAudio}/>
      </>}
      {tab!=='import'&&<>
        <div className="as-voice-row"><div className="as-field as-voice-picker" ref={voiceMenuRef}><label>Escolha a voz</label><button className="as-select-button" aria-expanded={voiceMenu} aria-controls="voice-menu" disabled={connection!=='connected'||busy||saving} onClick={()=>setVoiceMenu(value=>!value)}><span className="as-voice-avatar">{selectedVoice?.name.slice(0,2)||<Mic2 size={15}/>}</span><span className="as-select-copy"><strong>{selectedVoice?.name||initialProject?.voiceName||(settings.voiceId?'Voz selecionada':'Biblioteca de vozes')}</strong><span>{selectedVoice?isBrazilian(selectedVoice)?'Identificada como brasileira':isPortuguese(selectedVoice)?'Português · confira o sotaque':'Confira o idioma e sotaque':connection==='connected'?'Prefira uma voz brasileira':'Configure ElevenLabs para escolher'}</span></span><ChevronDown size={14}/></button>
          {voiceMenu&&<div className="as-voice-menu" id="voice-menu"><div className="as-search"><Search size={14}/><input aria-label="Buscar voz" placeholder="Nome, sotaque ou estilo" value={voiceQuery} onChange={event=>setVoiceQuery(event.target.value)} autoFocus/></div><div className="as-voice-filters" role="group" aria-label="Idioma das vozes"><button aria-pressed={voiceFilter==='portuguese'} className={voiceFilter==='portuguese'?'active':''} onClick={()=>setVoiceFilter('portuguese')}>Português / Brasil</button><button aria-pressed={voiceFilter==='all'} className={voiceFilter==='all'?'active':''} onClick={()=>setVoiceFilter('all')}>Todas</button></div><div className="as-voice-menu-list">{filteredVoices.map(voice=><div className={'as-voice-option '+(settings.voiceId===voice.id?'active':'')} key={voice.id}><button aria-pressed={settings.voiceId===voice.id} onClick={()=>{patch({voiceId:voice.id});setVoiceMenu(false);sampleRef.current?.pause();}}><span className="as-voice-avatar">{voice.name.slice(0,2)}</span><span><strong>{voice.name}</strong><span className="as-voice-description">{isBrazilian(voice)?'Português brasileiro · ':''}{voice.description||Object.values(voice.labels).slice(0,3).join(' · ')||'Voz da sua conta'}</span></span>{settings.voiceId===voice.id&&<Check size={13}/>}</button>{voice.previewUrl&&<button className="as-voice-sample" onClick={()=>previewVoice(voice)} aria-label={'Ouvir amostra de '+voice.name} title="Amostra existente da biblioteca"><Play size={12}/></button>}</div>)}{!filteredVoices.length&&<p className="as-empty-search">Nenhuma voz identificada neste filtro. Confira “Todas” ou carregue mais vozes.</p>}</div>{nextVoicePage&&<button className="as-voice-menu-footer" disabled={loadingVoices} onClick={loadMoreVoices}>{loadingVoices?'Carregando…':'Carregar mais vozes'}</button>}</div>}
          {voices.some(voice=>voice.id===telegramVoiceId)&&<button className="as-text-action as-telegram-voice" disabled={busy||saving} onClick={()=>{patch({voiceId:telegramVoiceId,mood:'natural'});sampleRef.current?.pause();onNotify('Voz do Telegram selecionada com estabilidade Natural.');}}>{settings.voiceId===telegramVoiceId?<Check size={12}/>:<Mic2 size={12}/>}Voz do seu Telegram</button>}
        </div>{tab==='create'&&<div className="as-field"><label>Estabilidade</label><div className="as-moods" role="group" aria-label="Estabilidade da voz">{[{id:'natural',name:'Natural'},{id:'soft',name:'Consistente'},{id:'expressive',name:'Expressiva'}].map(mood=><button key={mood.id} aria-pressed={settings.mood===mood.id} disabled={busy||saving} className={settings.mood===mood.id?'active':''} onClick={()=>patch({mood:mood.id as Settings['mood']})}>{mood.name}</button>)}</div></div>}</div>
        {tab==='create'&&<div className="as-line-preview"><button className="as-secondary-button" disabled={busy||saving||connection!=='connected'||!settings.voiceId||!settings.text.trim()} onClick={previewActualLine}>{linePreviewing?<LoaderCircle size={14} className="spin"/>:<Headphones size={14}/>}Gerar prévia da frase</button><small>Usa créditos da conta · até 240 caracteres</small>{linePreview&&<div className="as-line-player"><audio ref={linePlayer} src={lineUrl||undefined} onPlay={()=>setLinePlaying(true)} onPause={()=>setLinePlaying(false)} onEnded={()=>setLinePlaying(false)}/><button className="as-voice-sample" aria-label={linePlaying?'Parar prévia da frase':'Ouvir prévia da frase'} onClick={toggleLine}>{linePlaying?<Pause size={12}/>:<Play size={12}/>}</button><span>Prévia de {linePreview.name}</span><button className="as-text-action" onClick={()=>downloadStem(linePreview.blob,'previa')} aria-label="Baixar prévia"><ArrowDownToLine size={13}/></button></div>}</div>}
      </>}
      <div className="as-divider"/>
      <section className="as-environments" aria-label="Escolher lugar"><div className="as-section-heading"><span className="as-title">Onde acontece?</span><button className="as-text-action" aria-expanded={allEnvironments} onClick={()=>{setAllEnvironments(value=>!value);setCategory('all');setEnvironmentQuery('');}}>{allEnvironments?'Recolher':environments.length+' lugares'}{allEnvironments?<ChevronUp size={13}/>:<ChevronDown size={13}/>}</button></div>
        {allEnvironments&&<div className="as-environment-tools"><div className="as-search"><Search size={14}/><input aria-label="Buscar ambiente" placeholder="Chuva, rua, banheiro…" value={environmentQuery} onChange={event=>setEnvironmentQuery(event.target.value)}/></div><div className="as-category-list" role="group" aria-label="Categoria de ambiente">{environmentCategories.map(item=><button key={item.id} className={category===item.id?'active':''} aria-pressed={category===item.id} onClick={()=>setCategory(item.id)}>{item.label}</button>)}</div></div>}
        <div className="as-environment-grid">{filteredEnvironments.map(environment=><button key={environment.id} className={'as-environment-button '+(settings.environment===environment.id?'selected':'')} aria-pressed={settings.environment===environment.id} disabled={busy||saving} onClick={()=>selectEnvironment(environment.id)}><EnvironmentEmoji environment={environment.id} size={28}/><span>{environment.name}</span></button>)}</div>{!filteredEnvironments.length&&<p className="as-empty-search">Nenhum lugar encontrado.</p>}
        <div className="as-environment-detail"><div className="as-sound-status"><span className={selectedReadiness?.reviewed?'reviewed':''}/>{soundStatus}<button aria-label="Atualizar biblioteca de ambientes" onClick={()=>void refreshReadiness()}><Settings2 size={13}/></button></div><p>{ambientMode==='custom'?customAmbient?.name:selectedReadiness?.provenance?.label||selectedEnvironment.sound.signature.join(' · ')}</p>{ambientMode==='scene'&&selectedReadiness?.provenance&&<details className="as-provenance"><summary>Fonte da gravação<ChevronDown size={11}/></summary><span>{selectedReadiness.provenance.license} · {selectedReadiness.reviewed?'Revisada na biblioteca':'Confira o conteúdo antes de usar'}</span><div>{sourceLink(selectedReadiness.provenance.source)&&<a href={sourceLink(selectedReadiness.provenance.source)} target="_blank" rel="noreferrer">Ver fonte original</a>}{sourceLink(selectedReadiness.provenance.licenseUrl)&&<a href={sourceLink(selectedReadiness.provenance.licenseUrl)} target="_blank" rel="noreferrer">Licença</a>}</div></details>}{silentEnvironment?<small>{selectedReadiness?.resources?.ir?'Acústica gravada do lugar, aplicada automaticamente. Sem fundo acrescentado.':'Os reflexos mudam a voz. Nenhum fundo é acrescentado.'}</small>:<div className="as-sound-detail-actions"><button className="as-text-action" disabled={busy||saving} onClick={()=>toggleAmbient(false,!hasPreparedSound&&connection==='connected')}>{ambientPlaying&&previewKind==='real'?<Pause size={13}/>:<Headphones size={13}/>} {ambientPlaying&&previewKind==='real'?'Parar ambiente':hasPreparedSound?'Ouvir ambiente':'Gerar som do ambiente'}</button>{!hasPreparedSound&&<small>{connection==='connected'?'A geração usa créditos.':'Adicione um arquivo próprio ou configure ElevenLabs.'}</small>}{ambientMode==='scene'&&<button className="as-text-action" disabled={busy||saving} onClick={()=>toggleAmbient(true)}>{ambientPlaying&&previewKind==='illustrative'?'Parar ilustração':'Ilustração local'}</button>}</div>}{ambientPlaying&&<small className="as-preview-caption" role="status">{ambientPreparing?'Preparando prévia…':previewKind==='illustrative'?'Som sintético ilustrativo; não entra no mix.':'Ouvindo o arquivo de ambiente.'}</small>}</div>
        <div className="as-custom-bed"><div><strong>Tem o som desse lugar?</strong><span>Importe uma gravação e ajuste o mix localmente.</span></div><button className="as-secondary-button" disabled={busy||saving||finalOnly} onClick={()=>ambientInput.current?.click()}><Upload size={13}/>{customAmbient?'Trocar arquivo':'Importar fundo'}</button></div><input ref={ambientInput} type="file" accept="audio/*,.wav,.mp3,.m4a,.ogg,.flac" hidden onChange={event=>void importLocalResource(event,'ambience')}/>
        {customAmbient&&<div className="as-custom-bed-active"><div className="as-small-segment" role="group" aria-label="Fonte do ambiente"><button aria-pressed={ambientMode==='scene'} className={ambientMode==='scene'?'active':''} disabled={busy||saving} onClick={()=>{stopPreview();setAmbientMode('scene');patch({ambientVolume:selectedEnvironment.sound.defaultVolume});}}>Som do lugar</button><button aria-pressed={ambientMode==='custom'} className={ambientMode==='custom'?'active':''} disabled={busy||saving} onClick={()=>{stopPreview();setAmbientMode('custom');patch({ambientVolume:settings.ambientVolume||30});}}>Meu arquivo</button></div><small>{customAmbient.name} · {customAmbient.buffer?formatTime(customAmbient.buffer.duration):''}</small></div>}
      </section>
      <button className="as-advanced-button" aria-expanded={advanced} aria-controls="as-advanced-settings" onClick={()=>setAdvanced(value=>!value)}><Settings2 size={14}/>Qualidade e acústica{advanced?<ChevronUp size={14}/>:<ChevronDown size={14}/>}</button>
      {advanced&&<div className="as-advanced" id="as-advanced-settings">
        {tab!=='import'&&<div className="as-field"><label>Qualidade da geração</label><div className="as-quality" role="group" aria-label="Qualidade da geração"><button className={settings.quality==='lossless'?'active':''} aria-pressed={settings.quality==='lossless'} disabled={busy||saving} onClick={()=>patch({quality:'lossless'})}>Sem compressão</button><button className={settings.quality==='standard'?'active':''} aria-pressed={settings.quality==='standard'} disabled={busy||saving} onClick={()=>patch({quality:'standard'})}>Arquivo compacto</button></div><p className="as-field-help">{settings.quality==='lossless'?'Voz original em WAV, 24 kHz e 16 bits. Preserva as amostras recebidas da ElevenLabs.':'Voz em MP3, 128 kbps. Ocupa menos espaço.'} O mix final é exportado em WAV de 48 kHz. {tab==='guide'&&settings.quality==='lossless'?'Interpretações: até '+losslessGuideSeconds+' segundos.':settings.quality==='lossless'?'Roteiros: até '+losslessMaxChars+' caracteres.':''}</p></div>}
        <div className="as-switch-row"><div><strong>Acústica do lugar</strong><span>{!settings.spatial?'Acústica desligada. A fala fica sem os reflexos do lugar.':impulse?'Resposta de sala aplicada à voz.':'A resposta gravada deste lugar será aplicada automaticamente, quando disponível.'}</span></div><button role="switch" aria-label="Ativar acústica do lugar" aria-checked={settings.spatial} disabled={busy||saving||finalOnly} onClick={toggleSpatial}><span className="as-switch-knob"/></button></div>
        <div className="as-ir-panel"><div className="as-section-heading"><span className="as-title">Resposta de sala (IR)</span>{impulse&&<button className="as-text-action" disabled={busy||saving||finalOnly} onClick={()=>{setImpulse(null);if(tracks)setTracks({...tracks,id:crypto.randomUUID(),impulse:undefined});}}>Remover<X size={12}/></button>}</div><p>A acústica gravada do cenário entra automaticamente. Você também pode importar uma resposta própria.</p><div className="as-guide-actions">{selectedReadiness?.resources?.ir&&<button className="as-secondary-button" disabled={busy||saving||finalOnly} onClick={loadSceneImpulse}><AudioLines size={13}/>Usar resposta do lugar</button>}<button className="as-secondary-button" disabled={busy||saving||finalOnly} onClick={()=>impulseInput.current?.click()}><Upload size={13}/>{impulse?'Trocar IR':'Importar IR'}</button></div><input ref={impulseInput} type="file" accept=".wav,.flac,.mp3,.ogg,audio/*" hidden onChange={event=>void importLocalResource(event,'impulse')}/><small>Mono ou estéreo · até 4 segundos e 8 MB</small>
        {impulse&&<><div className="as-ir-file"><strong>{impulse.name}</strong><span>{impulse.buffer.duration<1?Math.round(impulse.buffer.duration*1000)+' ms':impulse.buffer.duration.toFixed(2)+' s'} · {impulse.buffer.numberOfChannels===1?'mono':'estéreo'} · {(impulse.buffer.sampleRate/1000).toFixed(1)} kHz</span><small>{impulse.source==='library'&&impulse.reviewed?'Resposta revisada da biblioteca.':impulse.source==='recording'?'Resposta de sala incluída, ainda não revisada.':'Arquivo importado, sem verificação de origem ou medição.'}</small></div><div className="as-slider-row"><label htmlFor="as-ir-wet" className="as-slider-label">Intensidade da sala<strong>{Math.round(settings.ir.wet*100)}%</strong></label><input id="as-ir-wet" type="range" min="0" max=".65" step=".01" disabled={busy||saving||finalOnly||!settings.spatial} value={settings.ir.wet} onChange={event=>patch({ir:{...settings.ir,wet:Number(event.target.value)}})}/></div><label className="as-checkbox"><input type="checkbox" checked={settings.ir.directSound==='included'} disabled={busy||saving||finalOnly} onChange={event=>patch({ir:{...settings.ir,directSound:event.target.checked?'included':'removed'}})}/><span>Remover a chegada direta da IR<small>Ative apenas se o arquivo contém o som direto além dos reflexos.</small></span></label>{settings.ir.directSound==='included'&&<div className="as-number-grid"><label>Chegada direta (ms)<input type="number" min="0" max="500" value={settings.ir.directArrivalMs} disabled={busy||saving||finalOnly} onChange={event=>patch({ir:{...settings.ir,directArrivalMs:clamp(event.target.valueAsNumber,0,500,0)}})}/></label><label>Janela a remover (ms)<input type="number" min=".5" max="30" step=".5" value={settings.ir.directWindowMs} disabled={busy||saving||finalOnly} onChange={event=>patch({ir:{...settings.ir,directWindowMs:clamp(event.target.valueAsNumber,.5,30,5)}})}/></label></div>}<div className="as-field"><label htmlFor="as-ir-delay">Tempo antes dos reflexos</label><select id="as-ir-delay" value={settings.ir.predelayMode} disabled={busy||saving||finalOnly} onChange={event=>patch({ir:{...settings.ir,predelayMode:event.target.value as ImpulseControls['predelayMode']}})}><option value="embedded">Já está no arquivo</option><option value="external">Aplicar manualmente</option></select></div>{settings.ir.predelayMode==='external'&&<label className="as-number-single">Atraso a aplicar (ms)<input type="number" min="0" max="200" value={settings.ir.predelayMs} disabled={busy||saving||finalOnly} onChange={event=>patch({ir:{...settings.ir,predelayMs:clamp(event.target.valueAsNumber,0,200,0)}})}/></label>}<small>O arquivo substitui os reflexos calculados. O atraso não é aplicado duas vezes.</small></>}
        </div>
      </div>}
      {error&&<div className="as-inline-error" role="alert">{error}<button aria-label="Fechar aviso" onClick={()=>setError('')}><X size={14}/></button></div>}
      <div className="as-generate-actions">{tab==='import'?<button className="as-generate-button" disabled={busy||saving||mixing||!tracks} onClick={applyEnvironment}>{busy?<LoaderCircle className="spin" size={17}/>:<AudioLines size={17}/>} {busy?stageText:'Aplicar este lugar'}<span>{ambientMode==='custom'||silentEnvironment||hasPreparedSound?'Mix local':'Fundo com IA'}</span></button>:<button className="as-generate-button" disabled={busy||saving||mixing||losslessOverLimit||connection!=='connected'||!settings.voiceId||(tab==='guide'?!guide:!settings.text.trim())} onClick={generate}>{busy?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>} {busy?stageText:tab==='guide'?'Converter minha interpretação':'Criar áudio'}<span>{tab==='guide'?'Voice Changer v2':'Eleven v3'}</span></button>}{(stage==='voice'||stage==='ambience'||linePreviewing)&&<button className="as-secondary-button" onClick={cancel}>Parar espera</button>}</div>
      <p className="as-action-note">{losslessOverLimit&&tab==='guide'?'Sem compressão aceita até '+losslessGuideSeconds+' segundos. Recorte a guia ou escolha Arquivo compacto.':tab==='import'?'Volume, captura e acústica reutilizam suas faixas. Um fundo ausente só é gerado quando você aplica o lugar.':'Criar voz ou converter interpretação usa créditos ElevenLabs. Ajustar o mix depois reutiliza as mesmas faixas.'}</p>
      {connection!=='connected'&&tab!=='import'&&<button className="as-connect-help" onClick={()=>setSetupOpen(true)}>Configurar conexão para gerar<Settings2 size={12}/></button>}
    </section>
    <aside className="as-preview" aria-label="Ouvir e ajustar o mix"><div className="as-preview-header"><h2>Seu áudio</h2><span className="as-source-tag">{result?result.source==='voice-changer'?'Interpretação convertida':result.source==='elevenlabs'?'Eleven v3':'Voz importada':'Prévia e mix'}</span></div>
      <div className={'as-preview-visual '+(playing?'playing':'')}>{result?<div className="as-waveform" aria-hidden="true">{peaks.map((height,index)=><i key={index} style={{height:Math.min(height,48)+'px'}}/>)}</div>:<div className="as-preview-empty"><AudioLines size={28}/><span>Uma voz para começar.</span><small>Seu resultado aparece aqui.</small></div>}</div>
      <div className="as-preview-copy"><EnvironmentEmoji environment={result?.environment||selectedEnvironment.id} size={29}/><div><h3>{result?getEnvironment(result.environment).name:selectedEnvironment.name}</h3><p>{result?result.voiceName:'Escolha a voz e o lugar.'}</p></div></div>
      {result&&<><div className="as-comparison" role="group" aria-label="Comparar as faixas"><button className={comparison==='mix'?'active':''} aria-pressed={comparison==='mix'} onClick={()=>setComparison('mix')}>Mix final</button><button className={comparison==='voice'?'active':''} aria-pressed={comparison==='voice'} disabled={!result.tracks} onClick={()=>setComparison('voice')}>Só voz</button>{result.tracks?.guide&&<button className={comparison==='guide'?'active':''} aria-pressed={comparison==='guide'} onClick={()=>setComparison('guide')}>Guia original</button>}</div><audio ref={playerRef} src={resultUrl||undefined} onTimeUpdate={event=>setCurrentTime(event.currentTarget.currentTime)} onEnded={()=>setPlaying(false)} onPause={()=>setPlaying(false)} onPlay={()=>setPlaying(true)}/><div className="as-audio-player"><button className="as-play-button" aria-label={playing?'Pausar áudio':'Reproduzir faixa selecionada'} disabled={mixing||busy} onClick={togglePlay}>{playing?<Pause size={17} fill="currentColor"/>:<Play size={17} fill="currentColor"/>}</button><div className="as-seek"><input aria-label="Posição do áudio" type="range" min="0" max={playbackClip?.buffer.duration||0} step=".1" value={Math.min(currentTime,playbackClip?.buffer.duration||0)} onChange={event=>{if(playerRef.current){playerRef.current.currentTime=Number(event.target.value);setCurrentTime(Number(event.target.value));}}}/><div className="as-time"><span>{formatTime(currentTime)}</span><span>{formatTime(playbackClip?.buffer.duration||0)}</span></div></div></div><p className="as-comparison-note">A comparação aproxima o volume pela energia da fala. Não é uma medição de LUFS.</p></>}
      {busy&&<div className="as-stage" role="status"><LoaderCircle size={14} className="spin"/>{stageText}</div>}{mixing&&!busy&&<div className="as-stage" role="status"><LoaderCircle size={14} className="spin"/>Atualizando o mix local…</div>}
      {pending&&!busy&&<div className="as-pending-mix"><span>Há um novo lugar ou fundo selecionado.</span><button onClick={applyEnvironment} disabled={mixing||saving}>Aplicar ao áudio<AudioLines size={13}/></button><small>{ambientMode==='custom'||silentEnvironment||hasPreparedSound?'Sua voz será reutilizada.':'Sua voz será reutilizada; o fundo ausente poderá usar créditos.'}</small></div>}
      <div className="as-mix-panel"><div className="as-section-heading"><span className="as-title">Ajuste a sensação.</span><SlidersHorizontal size={14}/></div>
        <div className="as-field"><label>Captura</label><div className="as-small-segment" role="group" aria-label="Perfil de captura"><button className={settings.capture==='clean'?'active':''} aria-pressed={settings.capture==='clean'} disabled={busy||saving||finalOnly} onClick={()=>patch({capture:'clean'})}>Limpa</button><button className={settings.capture==='mobile'?'active':''} aria-pressed={settings.capture==='mobile'} disabled={busy||saving||finalOnly} onClick={()=>patch({capture:'mobile'})}>Celular</button></div><small className="as-inline-help">{settings.capture==='mobile'?'Coloração de microfone de celular aplicada no mix.':'Voz clara, com a dinâmica da faixa preservada.'}</small></div>
        <div className="as-field"><label>Posição da voz</label><div className="as-small-segment" role="group" aria-label="Perspectiva do microfone">{[{id:'close',name:'Perto'},{id:'natural',name:'Natural'},{id:'distant',name:'Distante'}].map(item=><button key={item.id} className={settings.perspective===item.id?'active':''} aria-pressed={settings.perspective===item.id} disabled={busy||saving||finalOnly} onClick={()=>patch({perspective:item.id as Settings['perspective']})}>{item.name}</button>)}</div></div>
        {[{key:'voiceVolume',label:'Voz'},{key:'ambientVolume',label:'Fundo'}].map(row=><div className={'as-slider-row '+(row.key==='ambientVolume'&&silentEnvironment?'as-muted-control':'')} key={row.key}><label className="as-slider-label" htmlFor={'mix-'+row.key}>{row.label}<strong>{row.key==='ambientVolume'&&silentEnvironment?'Silencioso':settings[row.key as 'voiceVolume'|'ambientVolume']+'%'}</strong></label><input id={'mix-'+row.key} type="range" min="0" max="100" value={settings[row.key as 'voiceVolume'|'ambientVolume']} onChange={event=>patch({[row.key]:Number(event.target.value)})} disabled={busy||saving||finalOnly||(row.key==='ambientVolume'&&silentEnvironment)} style={{'--range-fill':settings[row.key as 'voiceVolume'|'ambientVolume']+'%'} as CSSProperties}/></div>)}
        <div className="as-switch-row"><div><strong>Priorizar a voz</strong><span>Reduz o fundo durante a fala.</span></div><button role="switch" aria-label="Priorizar a voz no mix" aria-checked={settings.ducking} onClick={()=>patch({ducking:!settings.ducking})} disabled={busy||saving||finalOnly||silentEnvironment}><span className="as-switch-knob"/></button></div>
        {tracks&&<span className="as-local-mix"><Check size={12}/>Ajustes locais · sem gerar outra voz</span>}
      </div>
      <div className="as-result-actions"><button className="as-export-button" disabled={!result||busy||mixing} onClick={download}><ArrowDownToLine size={15}/>Baixar WAV</button><button className="as-save-button" disabled={!result||busy||mixing||saving||saved} onClick={save}>{saving?<LoaderCircle size={15} className="spin"/>:saved?<Check size={15}/>:<FolderUp size={15}/>} {saving?'Salvando…':saved?'Salvo':'Salvar projeto'}</button></div>
      {result?.tracks&&<details className="as-stems"><summary>Baixar faixas separadas<ChevronDown size={12}/></summary><div><button onClick={()=>downloadStem(result.tracks!.voiceBlob,'voz')}><ArrowDownToLine size={12}/>Voz</button>{result.tracks.ambienceBlob&&<button onClick={()=>downloadStem(result.tracks!.ambienceBlob!,'ambiente')}><ArrowDownToLine size={12}/>Ambiente</button>}{result.tracks.guide&&<button onClick={()=>downloadStem(result.tracks!.guide!.blob,'guia')}><ArrowDownToLine size={12}/>Guia</button>}</div></details>}
      <div className="as-render-meta"><span>WAV · 48 kHz · estéreo</span>{metrics&&<span>{formatTime(metrics.duration)} · {Math.round(result!.blob.size/1024)} KB</span>}</div>
      {metrics&&<div className="as-quality-readout"><span>Pico de amostra</span><strong>{metrics.peak>0?(20*Math.log10(metrics.peak)).toFixed(1):'−∞'} dBFS</strong></div>}
      <footer className="as-preview-footer"><Headphones size={14}/><p>{result?.ambientSource==='uploaded'?'Fundo próprio, sem revisão automática. O projeto guarda as faixas para você remixar.':result?.ambientSource==='recording'?'Gravação de ambiente incluída, ainda não revisada. Ouça o conteúdo antes de usar.':result?.ambientSource==='local'?'Este projeto antigo usa um fundo ilustrativo. Escolha uma gravação para substituir.':result?.ambientSource==='library'?'Fundo revisado da biblioteca. As faixas continuam separadas.':result?.ambientSource==='elevenlabs'?'Ambiente gerado por IA, ainda não revisado. Confira sons e repetição.':result?'O espaço aparece na acústica da voz. Nenhum fundo foi acrescentado.':'Comece com pouco fundo. O realismo depende da voz, da interpretação e do som escolhido.'}</p></footer>
    </aside></div>
    <AnimatePresence>{setupOpen&&<motion.div className="as-modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setSetupOpen(false)}><motion.div ref={modalRef} role="dialog" aria-modal="true" aria-labelledby="audio-setup-title" className="as-setup-modal" initial={{opacity:0,y:reduceMotion?0:10}} animate={{opacity:1,y:0}} onClick={event=>event.stopPropagation()}><button className="as-modal-close" aria-label="Fechar configuração" onClick={()=>setSetupOpen(false)}><X size={18}/></button><h2 id="audio-setup-title">Conexão do estúdio</h2>{connection==='connected'?<p>A conexão está ativa. Suas vozes estão disponíveis no estúdio.</p>:<p>O serviço de voz está temporariamente indisponível. Tente atualizar a conexão em alguns instantes.</p>}<p>Texto: Eleven v3. Interpretação guia: Voice Changer Multilingual v2. Gerações usam os créditos da conta; mix e importações locais funcionam sem gerar outra voz.</p><div className="as-setup-actions"><button className="as-generate-button" disabled={connection==='checking'} onClick={()=>void refreshConnection()}>{connection==='checking'?<LoaderCircle size={15} className="spin"/>:<Check size={15}/>}Atualizar conexão</button><button className="as-secondary-button" onClick={()=>setSetupOpen(false)}>Voltar</button></div><span className="as-field-help" role="status">{connection==='connected'?'Conexão ativa.':connection==='offline'?'O serviço de voz não respondeu. Tente novamente.':connection==='error'?'Não foi possível acessar o serviço de voz.':'Serviço de voz indisponível no momento.'}</span></motion.div></motion.div>}</AnimatePresence>
  </motion.div>;
}
